## name: Monokai Pro
## author: Wimer Hazenberg (monokai.pro)
## license: MIT
## upstream: https://monokai.pro/
## blurb: Monokai Pro default filter, ported for kitty

foreground            #fcfcfa
background            #2d2a2e
selection_foreground  #fcfcfa
selection_background  #5b595c

cursor                #fcfcfa
cursor_text_color     #2d2a2e

url_color             #78dce8

# black
color0                #403e41
color8                #727072

# red
color1                #ff6188
color9                #ff6188

# green
color2                #a9dc76
color10               #a9dc76

# yellow
color3                #ffd866
color11               #ffd866

# blue
color4                #fc9867
color12               #fc9867

# magenta
color5                #ab9df2
color13               #ab9df2

# cyan
color6                #78dce8
color14               #78dce8

# white
color7                #fcfcfa
color15               #fcfcfa

# tab bar
active_tab_foreground   #2d2a2e
active_tab_background   #ffd866
inactive_tab_foreground #939293
inactive_tab_background #221f22

# marks
mark1_foreground #2d2a2e
mark1_background #ff6188
mark2_foreground #2d2a2e
mark2_background #ffd866
mark3_foreground #2d2a2e
mark3_background #78dce8
