## name: Warm Burnout
## author: felipefdl
## license: MIT
## upstream: https://github.com/felipefdl/warm-burnout
## blurb: Warm, slightly burnt-out palette with one cool steel-patina accent

foreground            #bfbdb6
background            #1a1510
selection_foreground  #bfbdb6
selection_background  #33393a

cursor                #f5c56e
cursor_text_color     #1a1510

url_color             #90aec0

# black
color0                #23211b
color8                #686868

# red
color1                #f06b73
color9                #f07178

# green
color2                #70bf56
color10               #aad94c

# yellow
color3                #fdb04c
color11               #ffb454

# blue
color4                #4fbfff
color12               #59c2ff

# magenta
color5                #d0a1ff
color13               #d2a6ff

# cyan
color6                #93e2c8
color14               #95e6cb

# white
color7                #c7c7c7
color15               #ffffff

# tab bar
active_tab_foreground   #1a1510
active_tab_background   #ffb454
inactive_tab_foreground #b4a89c
inactive_tab_background #14120f

# marks
mark1_foreground #1a1510
mark1_background #ff8f40
mark2_foreground #1a1510
mark2_background #f5c56e
mark3_foreground #1a1510
mark3_background #90aec0
